### ISSUE TITLE
Layouts & templates?

### ISSUE THREAD

**Issue by safetypins** [kenjis/codeigniter-ss-twig#15]
I'm unfamiliar with CodeIgniter (just learning) but I see some stuff elsewhere on the web referencing templates and layouts in CI 2, and specifically with the older twiggy (http://stackoverflow.com/questions/19482485/using-twig-in-codeigniter-project). Does your integration of twig support this sort of template/layout configuration?

Can I configure a default layout that will always be rendered around the view content whenever I call:
`$this->twig->display('[view]',$data);`

**Comment by kenjis** [comment]
No. This is very simple integration of Twig. 
All this package provides is: https://github.com/kenjis/codeigniter-ss-twig#usage
This doesn't provide such a layout/template functionality, because Twig has no such functionality.

If you want such a layout/template system, you have to build it by yourself.

http://davidsosavaldes.github.io/Attire/ is another integration of Twig for CodeIgniter.
It has theme and layout system. But I don't know it fits your needs.
